name: Deploy to Hostinger
on:
  push:
    branches:
      - 17_github_action  # Altere 'main' para sua branch de produção, se for diferente (ex: 'master')
jobs:
  deploy:
    name: Deploy to public_html
    runs-on: ubuntu-latest # Usa a última versão do Ubuntu como ambiente de execução
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Deploy to Hostinger via SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HOSTINGER_SFTP_HOST }}
          username: ${{ secrets.HOSTINGER_SFTP_USERNAME }}
          password: ${{ secrets.HOSTINGER_SFTP_PASSWORD }}
          port: 65002
          source: "."
          target: "/home/u424791251/domains/admin.abertamente.net/public_html"
          rm: true


